version: '3.9'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports: 
      - "3000:53/tcp"
      - "3000:53/udp"
      - "80:80/tcp"
    environment:
      - TZ='America/Chicago'
      - PIHOLE_DNS_=unbound;9.9.9.9
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: unless-stopped